export const RentingProductsData = {
  beauty: [
    { name: "Radiant Complexion" },
    { name: "Skin Texture Smoothness" },
    { name: "Hydration and Moisture" },
    { name: "Skin Clarity and Clearness" },
    { name: "Elasticity and Firmness" },
  ],
  beautySub: [
    { name: "Glowing skin" },
    { name: "Healthy luminosity" },
    { name: "Natural radiance" },
    { name: "Youthful brightness" },
    { name: "Dewy appearance" },
    { name: "Other" },
  ],
  skinTexture: [
    { name: "Silk-like softness" },
    { name: "Pore refinement" },
    { name: "Flawless finish" },
    { name: "Velvety touch" },
    { name: "Even skin tone" },
    { name: "Other" },
  ],
  hydration: [
    { name: "Supple and plump" },
    { name: "Moisture retention" },
    { name: "Deep hydration" },
    { name: "Nourished skin" },
    { name: "Dewy suppleness" },
    { name: "Other" },
  ],
  skinClarity: [
    { name: "Blemish-free beauty" },
    { name: "Clear complexion" },
    { name: "Transparent skin" },
    { name: "Pimple-free radiance" },
    { name: "Dewy appearance" },
    { name: "Other" },
  ],
  elasticity: [
    { name: "Resilient skin" },
    { name: "Firm and toned" },
    { name: "Youthful bounce" },
    { name: "Elastic suppleness" },
    { name: "Tightened appearance" },
    { name: "Other" },
  ],
  bags: [
    { name: "Tote Bags" },
    { name: "Backpacks" },
    { name: "Crossbody Bags" },
    { name: "Clutch Purses" },
    { name: "Messenger Bags" },
    { name: "Duffel Bags" },
    { name: "Hobo Bags" },
    { name: "Satchel Bags" },
    { name: "Bucket Bags" },
    { name: "Wallets and Pouches" },
  ],
  toteBags: [
    { name: "Spacious and versatile" },
    { name: "Ideal for everyday use" },
    { name: "Durable materials available" },
    { name: "Fashionable designs" },
    { name: "Other" },
  ],
  backpacks: [
    { name: "Hands-free carrying option" },
    { name: "Great for commuting or travel" },
    { name: "Various sizes and styles" },
    { name: "Comfortable shoulder straps" },
    { name: "Other" },
  ],
  crossbody: [
    { name: "Adjustable crossbody strap" },
    { name: "Compact and easy to carry" },
    { name: "Perfect for on-the-go" },
    { name: "Stylish and functional" },
    { name: "Other" },
  ],
  clutch: [
    { name: "Small and elegant" },
    { name: "Evening or formal events" },
    { name: "Minimalist design" },
    { name: "Often handheld" },
    { name: "Other" },
  ],
  messenger: [
    { name: "Single shoulder strap" },
    { name: "Satchel-style design" },
    { name: "Popular for work or school" },
    { name: "Multiple compartments" },
    { name: "Other" },
  ],
  duffel: [
    { name: "Large and spacious" },
    { name: "Great for travel or sports" },
    { name: "Easy access to belongings" },
    { name: "Sturdy handles and straps" },
    { name: "Other" },
  ],
  hobo: [
    { name: "Slouchy, crescent shape" },
    { name: "Casual and bohemian style" },
    { name: "Comfortable to carry" },
    { name: "Roomy interior" },
    { name: "Other" },
  ],
  satchel: [
    { name: "Structured and chic" },
    { name: "Top handle and crossbody strap" },
    { name: "Professional appearance" },
    { name: "Organized compartments" },
    { name: "Other" },
  ],
  bucket: [
    { name: "Unique bucket shape" },
    { name: "Drawstring closure" },
    { name: "Trendy and spacious" },
    { name: "Casual yet fashionable" },
    { name: "Other" },
  ],
  wallets: [
    { name: "Compact for essentials" },
    { name: "Card slots and pockets" },
    { name: "Convenient for small items" },
    { name: "Often used as accessories" },
    { name: "Other" },
  ],
  awesome: [
    { name: "Lip Balm Flavors" },
    { name: "Lip Scrub Varieties" },
    { name: "Lip Mask Benefits" },
    { name: "Lip Sunscreen Protection" },
    { name: "Lip Tint Options" },
    { name: "Lip Care Tools" },
    { name: "Organic Lip Products" },
    { name: "Lip Care for Seasons" },
    { name: "Lip Care for Special Needs" },
    { name: "DIY Lip Care Recipes" },
  ],
  mobileTablets: [{ name: "Android" }, { name: "iOS" }],
  necklaces: [
    { name: "Chain Necklaces" },
    { name: "Layered Necklaces" },
    { name: "Pendant Necklaces" },
    { name: "Choker Necklaces" },
    { name: "Statement Necklaces" },
  ],
  clothing: [
    { name: "Tops" },
    { name: "Bottoms" },
    { name: "Outerwear" },
    { name: "Dresses" },
    { name: "Activewear" },
    { name: "Sleepwear" },
    { name: "Swimwear" },
    { name: "Workwear" },
    { name: "Baby clothing" },
    { name: "Uniforms" },
  ],
  bluetooth: [
    { name: "Bluetooth Classic" },
    { name: "Bluetooth Low Energy" },
    { name: "Bluetooth 5.0" },
    { name: "Bluetooth 5.1" },
    { name: "Bluetooth 5.2" },
    { name: "Bluetooth Mesh" },
    { name: "Bluetooth 5.3" },
  ],
  facial: [
    { name: "Cleansers and Scrubs" },
    { name: "Moisturizers and Serums" },
    { name: "Sun Protection" },
    { name: "Acne Treatment" },
    { name: "Face Masks and Peels" },
    { name: "Eye Care Products" },
    { name: "Facial Tools and Devices" },
    { name: "Toning and Astringents" },
    { name: "Makeup Removers" },
    { name: "Anti-Aging Products" },
  ],
  shoes: [
    { name: "Athletic Footwear" },
    { name: "Casual Footwear" },
    { name: "Formal Footwear" },
    { name: "Boots and Booties" },
    { name: "Sandals and Flip-Flops" },
    { name: "Outdoor and Hiking" },
    { name: "Work and Safety" },
    { name: "Specialty Footwear" },
    { name: "Fashion Sneakers" },
    { name: "Kids' Footwear" },
  ],
  cpu: [
    { name: "Central Processing Unit" },
    { name: "Microprocessors" },
    { name: "Multi-Core Processors" },
    { name: "Graphics Processing Unit" },
    { name: "Embedded Processors" },
    { name: "Server Processors" },
    { name: "Mobile Processors" },
    { name: "Desktop Processors" },
    { name: "Workstation CPUs" },
    { name: "Mainframe Processors" },
  ],
  discover: [
    { name: "Cleansing" },
    { name: "Moisturizing" },
    { name: "Discover Acne Treatment" },
    { name: "Discover Anti-Aging" },
    { name: "Discover Sun Protection" },
    { name: "Serums and Essences" },
    { name: "Masks and Treatments" },
    { name: "Eye Care" },
    { name: "Specialty Skincare" },
    { name: "Natural and Organic" },
  ],
  headphones: [
    { name: "Over-Ear Headphones" },
    { name: "In-Ear Earbuds" },
    { name: "On-Ear Headphones" },
    { name: "Wireless Bluetooth Headphones" },
    { name: "Gaming Headsets" },
    { name: "Studio Monitor Headphones" },
    { name: "Sports and Workout Earphones" },
    { name: "ANC Headphones" },
    { name: "DJ Headphones" },
    { name: "Open-Back Headphones" },
    { name: "Closed-Back Headphones" },
    { name: "Kids' Headphones" },
    { name: "Audiophile Headphones" },
  ],
  bracelets: [
    { name: "Metallic Bracelets" },
    { name: "Beaded Bracelets" },
    { name: "Leather Bracelets" },
    { name: "Charm Bracelets" },
    { name: "Friendship Bracelets" },
    { name: "Cuff Bracelets" },
    { name: "Chain Bracelets" },
    { name: "Bangle Bracelets" },
    { name: "Braided Bracelets" },
    { name: "Wrap Bracelets" },
  ],
  smartWatch: [
    { name: "Fitness Trackers" },
    { name: "Sport Watches" },
    { name: "Fashion Smartwatches" },
    { name: "GPS Running Watches" },
    { name: "Hybrid Smartwatches" },
    { name: "Kids' Smartwatches" },
    { name: "Luxury Smartwatches" },
    { name: "Outdoor Adventure Watches" },
    { name: "Medical Wearables" },
    { name: "Budget Smartwatches" },
  ],
  earrings: [
    { name: "Stud Earrings" },
    { name: "Hoop Earrings" },
    { name: "Dangle Earrings" },
    { name: "Huggee Earrings" },
    { name: "Ear Cuffs" },
    { name: "Threader Earrings" },
    { name: "Chandelier Earrings" },
    { name: "Clip-On Earrings" },
    { name: "Tassel Earrings" },
    { name: "Statement Earrings" },
  ],
  lipBalm: [
    { name: "Fruit-infused balms" },
    { name: "Minty fresh options" },
    { name: "Exotic tropical blends" },
    { name: "Natural, unscented choices" },
    { name: "Other" },
  ],
  lipScrub: [
    { name: "Sugar scrub options" },
    { name: "Exfoliating lip treatments" },
    { name: "Flavored scrub selections" },
    { name: "Gentle, sensitive formulas" },
    { name: "Other" },
  ],
  lipMusk: [
    { name: "Hydrating overnight masks" },
    { name: "Plumping lip treatments" },
    { name: "Nourishing, vitamin-rich masks" },
    { name: "Repairing cracked lip masks" },
    { name: "Other" },
  ],
  lipSunscreen: [
    { name: "SPF-infused lip balms" },
    { name: "Sunblock lip sticks" },
    { name: "UV lip protection" },
    { name: "Broad-spectrum SPF choices" },
    { name: "Other" },
  ],
  lipTint: [
    { name: "Sheer tinted lip balms" },
    { name: "Bold, pigmented lip stains" },
    { name: "Matte lip color choices" },
    { name: "Natural lip enhancers" },
    { name: "Other" },
  ],
  lipCare: [
    { name: "Lip scrub brushes" },
    { name: "Lip exfoliation pads" },
    { name: "Lip applicator wands" },
    { name: "Lip mask silicone molds" },
    { name: "Other" },
  ],
  organicLip: [
    { name: "All-natural lip balms" },
    { name: "Organic lip scrubs" },
    { name: "Chemical-free lip care" },
    { name: "Eco-friendly lip options" },
    { name: "Other" },
  ],
  lipCareSeasons: [
    { name: "Winter lip protection" },
    { name: "Summer sun care" },
    { name: "Fall lip hydration" },
    { name: "Spring lip renewal" },
    { name: "Other" },
  ],
  lipCareSpecial: [
    { name: "Sensitive skin solutions" },
    { name: "Vegan lip care products" },
    { name: "Gluten-free lip options" },
    { name: "Cruelty-free lip care" },
    { name: "Other" },
  ],
  android: [
    { name: "Samsung" },
    { name: "LG" },
    { name: "Sony" },
    { name: "Motorola" },
    { name: "Asus" },
    { name: "Lenovo" },
    { name: "TCL" },
    { name: "Honor" },
  ],
  iOS: [{ name: "Apple" }],

  chainNeckaces: [
    { name: "Cable Link Chains" },
    { name: "Figaro Chain Styles" },
    { name: "Rolo Chain Designs" },
    { name: "Snake Chain Varieties" },
    { name: "Other" },
  ],
  layeredNeckaces: [
    { name: "Multistrand Necklace Sets" },
    { name: "Mixed Metal Layering" },
    { name: "Delicate Layered Chains" },
    { name: "Personalized Layered Styles" },
    { name: "Other" },
  ],
  pandantNeckaces: [
    { name: "Gemstone Pendants" },
    { name: "Initial Letter Charms" },
    { name: "Religious Symbols" },
    { name: "Locket Pendant Styles" },
    { name: "Other" },
  ],
  chokerNeckaces: [
    { name: "Velvet Choker Trends" },
    { name: "Gothic Choker Designs" },
    { name: "Pearl Choker Styles" },
    { name: "Leather Choker Options" },
    { name: "Other" },
  ],
  statementNecklaces: [
    { name: "Bohemian Statement Pieces" },
    { name: "Crystal Statement Jewelry" },
    { name: "Geometric Statement Necklaces" },
    { name: "Vintage-inspired Statements" },
    { name: "Other" },
  ],
  tops: [
    { name: "T-shirts" },
    { name: "Blouses" },
    { name: "Hoodies" },
    { name: "Tank tops" },
    { name: "Other" },
  ],
  bottoms: [
    { name: "Jeans" },
    { name: "Leggings" },
    { name: "Shorts" },
    { name: "Trousers" },
    { name: "Other" },
  ],
  outerwear: [
    { name: "Jackets" },
    { name: "Coats" },
    { name: "Vests" },
    { name: "Raincoats" },
    { name: "Other" },
  ],
  dresses: [
    { name: "Evening gowns" },
    { name: "Maxi dresses" },
    { name: "Cocktail dresses" },
    { name: "Shift dresses" },
    { name: "Other" },
  ],
  activewear: [
    { name: "Yoga pants" },
    { name: "Running shorts" },
    { name: "Athletic shirts" },
    { name: "Compression leggings" },
    { name: "Other" },
  ],
  sleepwear: [
    { name: "Pajamas" },
    { name: "Nightgowns" },
    { name: "Sleep shirts" },
    { name: "Robes" },
    { name: "Other" },
  ],
  swimwear: [
    { name: "One-pieces" },
    { name: "Swim trunks" },
    { name: "Rash guards" },
    { name: "Cover-ups" },
    { name: "Other" },
  ],
  workwear: [
    { name: "Suits" },
    { name: "Dress shirts" },
    { name: "Slacks" },
    { name: "Work boots" },
    { name: "Other" },
  ],
  bClassic: [
    { name: "Legacy wireless technology" },
    { name: "Supports audio and data" },
    { name: "Common in older devices" },
    { name: "Other" },
  ],
  bLowEnergy: [
    { name: "Energy-efficient connectivity" },
    { name: "Ideal for IoT devices" },
    { name: "Lower data transfer rate" },
    { name: "Other" },
  ],
  bFive: [
    { name: "Improved range and speed" },
    { name: "Enhanced data throughput" },
    { name: "Better coexistence with Wi-Fi" },
    { name: "Other" },
  ],
  bFiveOne: [
    { name: "Precise location tracking" },
    { name: "Direction-finding capability" },
    { name: "Enhanced security features" },
    { name: "Other" },
  ],
  bFiveTwo: [
    { name: "Audio Sharing feature" },
    { name: "LE Audio improvements" },
    { name: "Enhanced multi-device support" },
    { name: "Other" },
  ],
  bMesh: [
    { name: "Mesh network topology" },
    { name: "Scalable IoT connectivity" },
    { name: "Reliable data transmission" },
    { name: "Other" },
  ],
  bFiveThree: [
    { name: "Future advancements expected" },
    { name: "Potential new features" },
    { name: "Improved efficiency and security" },
    { name: "Other" },
  ],
  cleansers: [
    { name: "Facial cleansers" },
    { name: "Exfoliating scrubs" },
    { name: "Micellar water" },
    { name: "Makeup removers" },
    { name: "Other" },
  ],

  uniforms: [
    { name: "School uniforms" },
    { name: "Military uniforms" },
    { name: "Medical scrubs" },
    { name: "Police uniforms" },
    { name: "Other" },
  ],

  babyClothing: [
    { name: "Onesies" },
    { name: "Baby rompers" },
    { name: "Infant socks" },
    { name: "Baby bibs" },
    { name: "Other" },
  ],

  serums: [
    { name: "Hydrating moisturizers" },
    { name: "Anti-aging serums" },
    { name: "Vitamin C serums" },
    { name: "Night creams" },
    { name: "Other" },
  ],

  sunProtection: [
    { name: "Sunscreen lotions" },
    { name: "SPF lip balms" },
    { name: "Sunscreen sprays" },
    { name: "After-sun care" },
    { name: "Other" },
  ],

  acne: [
    { name: "Acne cleansers" },
    { name: "Spot treatments" },
    { name: "Oil-free moisturizers" },
    { name: "Acne masks" },
    { name: "Other" },
  ],

  faceMasks: [
    { name: "Sheet masks" },
    { name: "Clay masks" },
    { name: "Chemical peels" },
    { name: "Hydrating masks" },
    { name: "Other" },
  ],

  eyeCare: [
    { name: "Eye creams" },
    { name: "Under-eye serums" },
    { name: "Eye gels" },
    { name: "Cooling eye masks" },
    { name: "Other" },
  ],

  facialTools: [
    { name: "Facial rollers" },
    { name: "Jade gua sha tools" },
    { name: "Derma rollers" },
    { name: "Electric cleansing brushes" },
    { name: "Other" },
  ],

  toning: [
    { name: "Facial toners" },
    { name: "Witch hazel" },
    { name: "Astringent solutions" },
    { name: "pH-balancing tonics" },
    { name: "Other" },
  ],

  makeup: [
    { name: "Makeup wipes" },
    { name: "Oil-based removers" },
    { name: "Micellar cleansing water" },
    { name: "Dual-phase removers" },
    { name: "Other" },
  ],
  antiAging: [
    { name: "Wrinkle creams" },
    { name: "Retinol treatments" },
    { name: "Collagen boosters" },
    { name: "Firming serums" },
    { name: "Other" },
  ],

  athletic: [
    { name: "Running Shoes" },
    { name: "Basketball Sneakers" },
    { name: "Soccer Cleats" },
    { name: "Cross Training Shoes" },
    { name: "Tennis Court Footwear" },
    { name: "Other" },
  ],

  casual: [
    { name: "Sneakers and Trainers" },
    { name: "Loafers and Slip-Ons" },
    { name: "Espadrilles and Flats" },
    { name: "Boat Shoes" },
    { name: "Moccasins" },
    { name: "Other" },
  ],
  formal: [
    { name: "Dress Shoes" },
    { name: "Oxfords and Brogues" },
    { name: "Derby Shoes" },
    { name: "Monk Strap Shoes" },
    { name: "Tuxedo Footwear" },
    { name: "Other" },
  ],

  bootsAndBooties: [
    { name: "Ankle Boots" },
    { name: "Knee-High Boots" },
    { name: "Chelsea Boots" },
    { name: "Hiking Boots" },
    { name: "Cowboy Boots" },
    { name: "Other" },
  ],

  sandals: [
    { name: "Slide Sandals" },
    { name: "Gladiator Sandals" },
    { name: "Thong Flip-Flops" },
    { name: "Wedge Sandals" },
    { name: "Espadrille Sandals" },
    { name: "Other" },
  ],

  outdoor: [
    { name: "Trail Running Shoes" },
    { name: "Mountaineering Boots" },
    { name: "Snow Boots" },
    { name: "Water Shoes" },
    { name: "Climbing Shoes" },
    { name: "Other" },
  ],

  workAndSafety: [
    { name: "Steel Toe Boots" },
    { name: "Slip-Resistant Shoes" },
    { name: "Electric Hazard Boots" },
    { name: "Chef's Shoes" },
    { name: "Nursing Clogs" },
    { name: "Other" },
  ],

  speciality: [
    { name: "Dance Shoes" },
    { name: "Bowling Shoes" },
    { name: "Cycling Shoes" },
    { name: "Golf Cleats" },
    { name: "Weightlifting Shoes" },
    { name: "Other" },
  ],

  fashion: [
    { name: "High-Top Sneakers" },
    { name: "Low-Top Sneakers" },
    { name: "Platform Sneakers" },
    { name: "Chunky Sneakers" },
    { name: "Retro Athletic Shoes" },
    { name: "Other" },
  ],

  kids: [
    { name: "Children's Sandals" },
    { name: "Toddler Sneakers" },
    { name: "School Uniform Shoes" },
    { name: "Infant Booties" },
    { name: "Youth Sports Shoes" },
    { name: "Other" },
  ],

  centralProcessing: [
    { name: "Core components of computers" },
    { name: "Executes instructions, performs calculations" },
    { name: "Brain of the computer system" },
    { name: "Handles data processing tasks" },
    { name: "Other" },
  ],

  microprocessors: [
    { name: "Compact CPU integrated circuits" },
    { name: "Power most personal devices" },
    { name: "Execute program instructions" },
    { name: "Vital for modern computing" },
    { name: "Other" },
  ],
  multiCore: [
    { name: "Multiple CPUs on one chip" },
    { name: "Enhance multitasking performance" },
    { name: "Improve overall processing speed" },
    { name: "Common in modern computers" },
    { name: "Other" },
  ],

  graphics: [
    { name: "Specialized for graphics rendering" },
    { name: "Accelerate 3D graphics tasks" },
    { name: "Vital for gaming and design" },
    { name: "Parallel processing capabilities" },
    { name: "Other" },
  ],
  embedded: [
    { name: "Found in everyday devices" },
    { name: "Power IoT devices" },
    { name: "Tailored for specific tasks" },
    { name: "Low power consumption" },
    { name: "Other" },
  ],

  server: [
    { name: "Designed for server tasks" },
    { name: "Handle heavy workloads" },
    { name: "Support multiple users" },
    { name: "Offer reliability and scalability" },
    { name: "Other" },
  ],
  mobileProcessors: [
    { name: "Power smartphones and tablets" },
    { name: "Optimize power efficiency" },
    { name: "Incorporate ARM architecture" },
    { name: "Enable mobile computing" },
    { name: "Other" },
  ],
  desktop: [
    { name: "Found in traditional PCs" },
    { name: "Balance performance and power" },
    { name: "Suitable for general tasks" },
    { name: "Overclocking capabilities" },
    { name: "Other" },
  ],
  workstation: [
    { name: "High-end for professional work" },
    { name: "Handle demanding applications" },
    { name: "Ideal for content creation" },
    { name: "Enhanced performance and reliability" },
    { name: "Other" },
  ],
  DIYLipCare: [
    { name: "Homemade lip balms" },
    { name: "DIY lip scrubs" },
    { name: "Natural lip mask ideas" },
    { name: "Custom lip care creations" },
    { name: "Other" },
  ],
  mainframe: [
    { name: "Large-scale computing systems" },
    { name: "Support critical operations" },
    { name: "High availability and reliability" },
    { name: "Serve enterprise-level needs" },
    { name: "Other" },
  ],
  cleansing: [
    { name: "Facial Cleansers" },
    { name: "Makeup Removers" },
    { name: "Exfoliating Scrubs" },
    { name: "Cleansing Oils" },
    { name: "Micellar Waters" },
    { name: "Other" },
  ],
  moisturizing: [
    { name: "Hydrating Creams" },
    { name: "Sunscreen Lotions" },
    { name: "Anti-Aging Serums" },
    { name: "Night Moisturizers" },
    { name: "Body Lotions" },
    { name: "Other" },
  ],
  acneTreatment: [
    { name: "Spot Treatments" },
    { name: "Acne Cleansers" },
    { name: "Salicylic Acid Products" },
    { name: "Benzoyl Peroxide Creams" },
    { name: "Tea Tree Oil Remedies" },
    { name: "Other" },
  ],
  discoverAntiAging: [
    { name: "Wrinkle Creams" },
    { name: "Collagen Boosters" },
    { name: "Retinol Serums" },
    { name: "Firming Moisturizers" },
    { name: "Peptide Formulas" },
    { name: "Other" },
  ],
  discoverSunProtection: [
    { name: "SPF Sunscreens" },
    { name: "Sunblock Lotions" },
    { name: "UV Protection Products" },
    { name: "Sunscreen Sprays" },
    { name: "After-Sun Care" },
    { name: "Other" },
  ],
  serumsAndEssences: [
    { name: "Hyaluronic Serums" },
    { name: "Vitamin C Boosters" },
    { name: "Niacinamide Essences" },
    { name: "Antioxidant Serums" },
    { name: "Skin-Brightening Treatments" },
    { name: "Other" },
  ],
  discoverMasks: [
    { name: "Sheet Masks" },
    { name: "Clay Masks" },
    { name: "Overnight Masks" },
    { name: "Chemical Peels" },
    { name: "Spot Treatment Patches" },
    { name: "Other" },
  ],
  discoverEyeCare: [
    { name: "Eye Creams" },
    { name: "Dark Circle Serums" },
    { name: "Anti-Puffiness Gels" },
    { name: "Eye Masks" },
    { name: "Lash and Brow Serums" },
    { name: "Other" },
  ],
  specialitySkincare: [
    { name: "Lip Balms" },
    { name: "Hand Creams" },
    { name: "Scar Treatment" },
    { name: "Tattoo Aftercare" },
    { name: "Foot Care Products" },
    { name: "Other" },
  ],
  nuturalAndOrganic: [
    { name: "Organic Skincare" },
    { name: "Vegan Formulas" },
    { name: "Clean Beauty" },
    { name: "Plant-Based Products" },
    { name: "Cruelty-Free Brands" },
    { name: "Other" },
  ],
  overEar: [
    { name: "Full-size ear cups" },
    { name: "Noise isolation" },
    { name: "Comfortable for long use" },
    { name: "Other" },
  ],
  inEar: [
    { name: "Compact and portable" },
    { name: "Noise-cancelling options" },
    { name: "Ideal for on-the-go" },
    { name: "Other" },
  ],
  onEar: [
    { name: "Smaller ear cups" },
    { name: "Lightweight and portable" },
    { name: "Good for daily commuting" },
    { name: "Other" },
  ],
  wirelessbluetooth: [
    { name: "Cordless convenience" },
    { name: "Great for workouts" },
    { name: "Range of styles available" },
    { name: "Other" },
  ],
  gamingHeadsets: [
    { name: "Built-in microphones" },
    { name: "Surround sound support" },
    { name: "Comfortable for gaming sessions" },
    { name: "Other" },
  ],
  studioMonitor: [
    { name: "High-fidelity audio" },
    { name: "Precise sound reproduction" },
    { name: "Preferred by audio professionals" },
    { name: "Other" },
  ],
  sportsAndWorkout: [
    { name: "Sweat-resistant design" },
    { name: "Secure fit during exercise" },
    { name: "In-line controls for music" },
    { name: "Other" },
  ],
  ANCHeadphones: [
    { name: "Blocks external noise" },
    { name: "Immersive audio experience" },
    { name: "Ideal for travel" },
    { name: "Other" },
  ],
  DJHeadphones: [
    { name: "Rotating ear cups" },
    { name: "Excellent sound clarity" },
    { name: "Durable for DJ use" },
    { name: "Other" },
  ],
  openBack: [
    { name: "Natural soundstage" },
    { name: "Less sound isolation" },
    { name: "Preferred for critical listening" },
    { name: "Other" },
  ],
  closedBack: [
    { name: "Enhanced noise isolation" },
    { name: "Minimal sound leakage" },
    { name: "Great for private listening" },
    { name: "Other" },
  ],
  kidsHeadphones: [
    { name: "Volume-limiting for safety" },
    { name: "Colorful and durable" },
    { name: "Kid-friendly designs" },
    { name: "Other" },
  ],
  audiophile: [
    { name: "High-end audio quality" },
    { name: "Premium materials" },
    { name: "Designed for audio enthusiasts" },
    { name: "Other" },
  ],
  beaded: [
    { name: "Gemstone Beads" },
    { name: "Wood and Seed Beads" },
    { name: "Other" },
  ],
  leather: [
    { name: "Braided Leather Bands" },
    { name: "Cuff Leather Straps" },
    { name: "Other" },
  ],
  charm: [
    { name: "Personalized Charms" },
    { name: "Vintage Charms" },
    { name: "Other" },
  ],
  friendship: [
    { name: "Woven Friendship Bands" },
    { name: "Matching Bracelet Sets" },
    { name: "Other" },
  ],
  metallic: [
    { name: "Gold, Silver, Copper" },
    { name: "Stainless Steel Bands" },
    { name: "Other" },
  ],
  cuff: [
    { name: "Wide Metal Cuffs" },
    { name: "Engraved Cuff Styles" },
    { name: "Other" },
  ],
  chain: [
    { name: "Link Chain Designs" },
    { name: "Delicate Chain Bracelets" },
    { name: "Other" },
  ],
  bangle: [
    { name: "Stacking Bangles" },
    { name: "Enamel Bangles" },
    { name: "Other" },
  ],
  braided: [
    { name: "Macrame Braids" },
    { name: "Paracord Bracelets" },
    { name: "Other" },
  ],
  wrap: [
    { name: "Leather Wrap Styles" },
    { name: "Boho Wrap Bands" },
    { name: "Other" },
  ],
  fitnessTrackers: [
    { name: "Health monitoring features" },
    { name: "Step counting capability" },
    { name: "Heart rate tracking" },
    { name: "Other" },
  ],
  sportWatches: [
    { name: "GPS for outdoor activities" },
    { name: "Workout-specific modes" },
    { name: "Robust durability" },
    { name: "Other" },
  ],
  fashionSmartwatches: [
    { name: "Stylish design options" },
    { name: "Customizable watch faces" },
    { name: "Accessory-focused" },
    { name: "Other" },
  ],
  gpsRunningWatches: [
    { name: "Precise location tracking" },
    { name: "Pace and distance metrics" },
    { name: "Training assistance" },
    { name: "Other" },
  ],
  hybridSmart: [
    { name: "Analog look with smart features" },
    { name: "Minimal digital display" },
    { name: "Long battery life" },
    { name: "Other" },
  ],
  kidsWatches: [
    { name: "Child safety features" },
    { name: "Limited communication" },
    { name: "Parental controls" },
    { name: "Other" },
  ],
  luxuryWatches: [
    { name: "Premium materials" },
    { name: "High-end craftsmanship" },
    { name: "Exclusive brand collaborations" },
    { name: "Other" },
  ],
  outdoorWatches: [
    { name: "Altitude and weather sensors" },
    { name: "Navigation tools" },
    { name: "Rugged ruction" },
    { name: "Other" },
  ],
  medicalWatches: [
    { name: "Health condition monitoring" },
    { name: "Medication reminders" },
    { name: "Emergency alerts" },
    { name: "Other" },
  ],
  budgetSmart: [
    { name: "Affordable price range" },
    { name: "Basic smart features" },
    { name: "Value for money" },
    { name: "Other" },
  ],
  studEarrings: [
    { name: "Diamond studs" },
    { name: "Pearl studs" },
    { name: "Gemstone studs" },
    { name: "Gold stud earrings" },
    { name: "other" },
  ],
  hoopEarrings: [
    { name: "Small hoop earrings" },
    { name: "Silver hoop earrings" },
    { name: "Diamond hoop earrings" },
    { name: "Bamboo hoop earrings" },
    { name: "other" },
  ],
  dangleEarrings: [
    { name: "Chandelier dangles" },
    { name: "Tassel dangle earrings" },
    { name: "Drop earrings" },
    { name: "Statement dangles" },
    { name: "other" },
  ],
  huggeeEarrings: [
    { name: "Mini huggie hoops" },
    { name: "CZ huggie earrings" },
    { name: "Thick huggie hoops" },
    { name: "Gold huggee earrings" },
    { name: "other" },
  ],
  earCuffs: [
    { name: "Cartilage ear cuffs" },
    { name: "Ear wrap cuffs" },
    { name: "Statement ear cuffs" },
    { name: "Crystal ear cuffs" },
    { name: "other" },
  ],
  threaderEarrings: [
    { name: "Chain threader earrings" },
    { name: "Bar threader earrings" },
    { name: "Long threader earrings" },
    { name: "Minimalist threaders" },
    { name: "other" },
  ],
  chandelierEarrings: [
    { name: "Vintage chandeliers" },
    { name: "Boho chandelier earrings" },
    { name: "Crystal chandeliers" },
    { name: "Bridal chandelier earrings" },
    { name: "other" },
  ],
  cliponEarrings: [
    { name: "Vintage clip-ons" },
    { name: "Clip-on hoop earrings" },
    { name: "Non-pierced earrings" },
    { name: "Pearl clip-on earrings" },
    { name: "other" },
  ],
  tasselEarrings: [
    { name: "Fringe tassel earrings" },
    { name: "Silk tassel earrings" },
    { name: "Beaded tassel dangles" },
    { name: "Bohemian tassel earrings" },
    { name: "other" },
  ],
  statementEarrings: [
    { name: "Oversized earrings" },
    { name: "Bold statement studs" },
    { name: "Dramatic drop earrings" },
    { name: "Exaggerated hoops" },
    { name: "other" },
  ],
};
