export const RentingCarData = [
  {
    id: 1,
    image: "RentingCar/car.png",
    title: "Lamborghini",
    price_day: "180",
    price_week: "925",
    price_month: "3,100",
    advantage1: "Luxury Limousine Selection",
    advantage2: "High Safety and Nudity",
    advantage3: "Fixed Price & Bonus System",
    advantage4: "100% Luxurious Fleet",
    advantage5: "Clean, Polite & Knowledgeable",
    advantage6: "Luxury Limousine Selection",
    taxes: "Incl.taxes",
    total_price: "230",
  },
  {
    id: 2,
    image: "RentingCar/car.png",
    title: "Ferrari",
    price_day: "250",
    price_week: "480",
    price_month: "3,100",
    advantage1: "Luxury Limousine Selection",
    advantage2: "High Safety and Nudity",
    advantage3: "Fixed Price & Bonus System",
    advantage4: "100% Luxurious Fleet",
    advantage5: "Clean, Polite & Knowledgeable",
    advantage6: "Luxury Limousine Selection",
    taxes: "Incl.taxes",
    total_price: "230",
  },
  {
    id: 3,
    image: "RentingCar/car.png",
    title: "Lamborghini",
    price_day: "180",
    price_week: "925",
    price_month: "3,100",
    advantage1: "Luxury Limousine Selection",
    advantage2: "High Safety and Nudity",
    advantage3: "Fixed Price & Bonus System",
    advantage4: "100% Luxurious Fleet",
    advantage5: "Clean, Polite & Knowledgeable",
    advantage6: "Luxury Limousine Selection",
    taxes: "Incl.taxes",
    total_price: "230",
  },
] as const;
